/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Nick Emanuel Salcedo Alfaro
 */
public class frmModCtrlMedicos extends javax.swing.JFrame {

    /**
     * Creates new form frmRegCtrlMedico
     */
    public frmModCtrlMedicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlTitulo = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        PnlInfMedico = new javax.swing.JPanel();
        LblInformeMedico = new javax.swing.JLabel();
        LblTalla = new javax.swing.JLabel();
        LblPeso = new javax.swing.JLabel();
        LblObservaciones = new javax.swing.JLabel();
        LblAnimal = new javax.swing.JLabel();
        TxtTalla = new javax.swing.JTextField();
        TxtAnimal = new javax.swing.JTextField();
        TxtPeso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaObservaciones = new javax.swing.JTextArea();
        PnlSecundario = new javax.swing.JPanel();
        ChbDiagnostico = new javax.swing.JCheckBox();
        ChbReceta = new javax.swing.JCheckBox();
        ChbSintoma = new javax.swing.JCheckBox();
        BtnModificarDiagnostico = new javax.swing.JToggleButton();
        PnlModificar = new javax.swing.JPanel();
        BtnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 620));

        LblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        LblTitulo.setText("Modificar Control Medico");

        javax.swing.GroupLayout PnlTituloLayout = new javax.swing.GroupLayout(PnlTitulo);
        PnlTitulo.setLayout(PnlTituloLayout);
        PnlTituloLayout.setHorizontalGroup(
            PnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblTitulo)
                .addGap(207, 207, 207))
        );
        PnlTituloLayout.setVerticalGroup(
            PnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTituloLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LblTitulo)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        LblInformeMedico.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        LblInformeMedico.setText("Informe Medico:");

        LblTalla.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        LblTalla.setText("Talla:");

        LblPeso.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        LblPeso.setText("Peso:");

        LblObservaciones.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        LblObservaciones.setText("Observaciones:");

        LblAnimal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        LblAnimal.setText("Animal:");

        TxtTalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTallaActionPerformed(evt);
            }
        });

        TxtAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAnimalActionPerformed(evt);
            }
        });

        TxtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPesoActionPerformed(evt);
            }
        });

        TxtAreaObservaciones.setColumns(20);
        TxtAreaObservaciones.setRows(5);
        jScrollPane1.setViewportView(TxtAreaObservaciones);

        javax.swing.GroupLayout PnlInfMedicoLayout = new javax.swing.GroupLayout(PnlInfMedico);
        PnlInfMedico.setLayout(PnlInfMedicoLayout);
        PnlInfMedicoLayout.setHorizontalGroup(
            PnlInfMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfMedicoLayout.createSequentialGroup()
                .addGroup(PnlInfMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlInfMedicoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PnlInfMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblObservaciones)
                            .addGroup(PnlInfMedicoLayout.createSequentialGroup()
                                .addGroup(PnlInfMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlInfMedicoLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(LblAnimal))
                                    .addComponent(LblPeso)
                                    .addComponent(LblTalla))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PnlInfMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1)))
                    .addGroup(PnlInfMedicoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(LblInformeMedico)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PnlInfMedicoLayout.setVerticalGroup(
            PnlInfMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInfMedicoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(LblInformeMedico)
                .addGap(18, 18, 18)
                .addGroup(PnlInfMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlInfMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTalla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PnlInfMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtPeso)
                    .addComponent(LblPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addComponent(LblObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        ChbDiagnostico.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        ChbDiagnostico.setText("Diagnostico");
        ChbDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChbDiagnosticoActionPerformed(evt);
            }
        });

        ChbReceta.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        ChbReceta.setText("Receta Medica");
        ChbReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChbRecetaActionPerformed(evt);
            }
        });

        ChbSintoma.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        ChbSintoma.setText("Sintomas");

        BtnModificarDiagnostico.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        BtnModificarDiagnostico.setText("Modificar Diagnostico");
        BtnModificarDiagnostico.setMargin(new java.awt.Insets(12, 14, 3, 14));
        BtnModificarDiagnostico.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BtnModificarDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarDiagnosticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlSecundarioLayout = new javax.swing.GroupLayout(PnlSecundario);
        PnlSecundario.setLayout(PnlSecundarioLayout);
        PnlSecundarioLayout.setHorizontalGroup(
            PnlSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlSecundarioLayout.createSequentialGroup()
                .addGap(0, 63, Short.MAX_VALUE)
                .addGroup(PnlSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ChbSintoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChbReceta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChbDiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BtnModificarDiagnostico))
                .addGap(61, 61, 61))
        );
        PnlSecundarioLayout.setVerticalGroup(
            PnlSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSecundarioLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ChbDiagnostico)
                .addGap(33, 33, 33)
                .addComponent(ChbReceta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(ChbSintoma)
                .addGap(40, 40, 40)
                .addComponent(BtnModificarDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        PnlModificar.setPreferredSize(new java.awt.Dimension(981, 80));

        BtnModificar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlModificarLayout = new javax.swing.GroupLayout(PnlModificar);
        PnlModificar.setLayout(PnlModificarLayout);
        PnlModificarLayout.setHorizontalGroup(
            PnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlModificarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlModificarLayout.setVerticalGroup(
            PnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlModificarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlInfMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(PnlModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PnlSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PnlInfMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PnlModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTallaActionPerformed

    private void TxtAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAnimalActionPerformed

    private void TxtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPesoActionPerformed

    private void ChbDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChbDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChbDiagnosticoActionPerformed

    private void ChbRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChbRecetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChbRecetaActionPerformed

    private void BtnModificarDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarDiagnosticoActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModCtrlMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModCtrlMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModCtrlMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModCtrlMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmModCtrlMedicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnModificar;
    private javax.swing.JToggleButton BtnModificarDiagnostico;
    private javax.swing.JCheckBox ChbDiagnostico;
    private javax.swing.JCheckBox ChbReceta;
    private javax.swing.JCheckBox ChbSintoma;
    private javax.swing.JLabel LblAnimal;
    private javax.swing.JLabel LblInformeMedico;
    private javax.swing.JLabel LblObservaciones;
    private javax.swing.JLabel LblPeso;
    private javax.swing.JLabel LblTalla;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlInfMedico;
    private javax.swing.JPanel PnlModificar;
    private javax.swing.JPanel PnlSecundario;
    private javax.swing.JPanel PnlTitulo;
    private javax.swing.JTextField TxtAnimal;
    private javax.swing.JTextArea TxtAreaObservaciones;
    private javax.swing.JTextField TxtPeso;
    private javax.swing.JTextField TxtTalla;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
