/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.time.LocalTime;

/**
 *
 * @author USUARIO
 */
public class frmMenuCtrlOperacion extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuCtrlMedico
     */
    public frmMenuCtrlOperacion() {
        initComponents();
        getContentPane().setBackground(new Color(241, 246, 190));
        this.setLocationRelativeTo(null);
        setResizable(false);
        setSize(1000, 620);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlTitulo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PnlVerCtrlMedico = new javax.swing.JPanel();
        LblSaludo = new javax.swing.JLabel();
        PnlInputs = new javax.swing.JPanel();
        PnlGenCrtlMed = new javax.swing.JPanel();
        BtnGenCtrlOpr = new javax.swing.JButton();
        PnlDelCtrlMed = new javax.swing.JPanel();
        BtnDelCtrlOpr = new javax.swing.JButton();
        PnlModCtrlMed = new javax.swing.JPanel();
        BtnModCtrlOpr = new javax.swing.JButton();
        PnlVerCtrlMed = new javax.swing.JPanel();
        BtnVerCtrlOpr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlTitulo.setBackground(new java.awt.Color(241, 246, 179));
        PnlTitulo.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(114, 187, 83));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gestión de controles de operaciones");
        PnlTitulo.add(jLabel3, new java.awt.GridBagConstraints());

        PnlVerCtrlMedico.setBackground(new java.awt.Color(241, 246, 179));

        LblSaludo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        LblSaludo.setForeground(new java.awt.Color(114, 187, 83));
        LblSaludo.setText("¡Buenas (Tiempo), (Nombre del veterinario)!");

        javax.swing.GroupLayout PnlVerCtrlMedicoLayout = new javax.swing.GroupLayout(PnlVerCtrlMedico);
        PnlVerCtrlMedico.setLayout(PnlVerCtrlMedicoLayout);
        PnlVerCtrlMedicoLayout.setHorizontalGroup(
            PnlVerCtrlMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlVerCtrlMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlVerCtrlMedicoLayout.setVerticalGroup(
            PnlVerCtrlMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlVerCtrlMedicoLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(LblSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        PnlInputs.setBackground(new Color(204, 255, 204));
        PnlInputs.setLayout(new java.awt.GridLayout(4, 1));

        PnlGenCrtlMed.setBackground(new java.awt.Color(241, 246, 179));
        PnlGenCrtlMed.setLayout(new java.awt.GridBagLayout());

        BtnGenCtrlOpr.setBackground(new java.awt.Color(26, 82, 118));
        BtnGenCtrlOpr.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnGenCtrlOpr.setForeground(new java.awt.Color(255, 255, 255));
        BtnGenCtrlOpr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/static/icon_create.png"))); // NOI18N
        BtnGenCtrlOpr.setText("Generar control de operación");
        BtnGenCtrlOpr.setToolTipText("");
        BtnGenCtrlOpr.setBorder(null);
        BtnGenCtrlOpr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnGenCtrlOpr.setPreferredSize(new java.awt.Dimension(700, 80));
        BtnGenCtrlOpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenCtrlOprActionPerformed(evt);
            }
        });
        PnlGenCrtlMed.add(BtnGenCtrlOpr, new java.awt.GridBagConstraints());

        PnlDelCtrlMed.setBackground(new java.awt.Color(241, 246, 179));
        PnlDelCtrlMed.setLayout(new java.awt.GridBagLayout());

        BtnDelCtrlOpr.setBackground(new java.awt.Color(211, 84, 0));
        BtnDelCtrlOpr.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnDelCtrlOpr.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelCtrlOpr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/static/icon_delete.png"))); // NOI18N
        BtnDelCtrlOpr.setText("Eliminar control de operaciones");
        BtnDelCtrlOpr.setPreferredSize(new java.awt.Dimension(700, 80));
        PnlDelCtrlMed.add(BtnDelCtrlOpr, new java.awt.GridBagConstraints());

        PnlModCtrlMed.setBackground(new java.awt.Color(241, 246, 179));
        PnlModCtrlMed.setLayout(new java.awt.GridBagLayout());

        BtnModCtrlOpr.setBackground(new java.awt.Color(114, 187, 83));
        BtnModCtrlOpr.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnModCtrlOpr.setForeground(new java.awt.Color(255, 255, 255));
        BtnModCtrlOpr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/static/icon_mod.png"))); // NOI18N
        BtnModCtrlOpr.setText("Modificar controles de operaciones");
        BtnModCtrlOpr.setPreferredSize(new java.awt.Dimension(700, 80));
        BtnModCtrlOpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModCtrlOprActionPerformed(evt);
            }
        });
        PnlModCtrlMed.add(BtnModCtrlOpr, new java.awt.GridBagConstraints());

        PnlVerCtrlMed.setBackground(new java.awt.Color(241, 246, 179));
        PnlVerCtrlMed.setLayout(new java.awt.GridBagLayout());

        BtnVerCtrlOpr.setBackground(new java.awt.Color(211, 84, 0));
        BtnVerCtrlOpr.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnVerCtrlOpr.setForeground(new java.awt.Color(255, 255, 255));
        BtnVerCtrlOpr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estilos/static/icon_read.png"))); // NOI18N
        BtnVerCtrlOpr.setText("Visualizar controles de operaciones");
        BtnVerCtrlOpr.setPreferredSize(new java.awt.Dimension(700, 80));
        PnlVerCtrlMed.add(BtnVerCtrlOpr, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PnlVerCtrlMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PnlInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PnlGenCrtlMed, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PnlVerCtrlMed, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PnlModCtrlMed, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PnlDelCtrlMed, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PnlVerCtrlMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PnlGenCrtlMed, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(PnlVerCtrlMed, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(PnlModCtrlMed, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(PnlDelCtrlMed, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PnlInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModCtrlOprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModCtrlOprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModCtrlOprActionPerformed

    private void BtnGenCtrlOprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenCtrlOprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGenCtrlOprActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuCtrlOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuCtrlOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuCtrlOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuCtrlOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuCtrlOperacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnDelCtrlOpr;
    public javax.swing.JButton BtnGenCtrlOpr;
    public javax.swing.JButton BtnModCtrlOpr;
    public javax.swing.JButton BtnVerCtrlOpr;
    public javax.swing.JLabel LblSaludo;
    private javax.swing.JPanel PnlDelCtrlMed;
    private javax.swing.JPanel PnlGenCrtlMed;
    private javax.swing.JPanel PnlInputs;
    private javax.swing.JPanel PnlModCtrlMed;
    private javax.swing.JPanel PnlTitulo;
    private javax.swing.JPanel PnlVerCtrlMed;
    private javax.swing.JPanel PnlVerCtrlMedico;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
