/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Nick Emanuel Salcedo Alfaro
 */
public class frmModCtrlOperaciones extends javax.swing.JFrame {

    /**
     * Creates new form frmRegCtrlOperacion
     */
    public frmModCtrlOperaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlRegistrarControlOperacion = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        PnlInformeMedicoLeft = new javax.swing.JPanel();
        LblInformeMedico = new javax.swing.JLabel();
        LblNombreOperacion = new javax.swing.JLabel();
        LblDescripcion = new javax.swing.JLabel();
        LblResultado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaDescripcion = new javax.swing.JTextArea();
        TxtAnimal = new javax.swing.JTextField();
        TxtNombreOperacion = new javax.swing.JTextField();
        TxtResultado = new javax.swing.JTextField();
        LblAnimal = new javax.swing.JLabel();
        PnlModificar = new javax.swing.JPanel();
        BtnModificar = new javax.swing.JToggleButton();
        PnlInformeMedicoRight = new javax.swing.JPanel();
        LblAnotaciones = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAreaAnotaciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlRegistrarControlOperacion.setPreferredSize(new java.awt.Dimension(1000, 100));

        LblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        LblTitulo.setText("Modificar control de operacion");

        javax.swing.GroupLayout PnlRegistrarControlOperacionLayout = new javax.swing.GroupLayout(PnlRegistrarControlOperacion);
        PnlRegistrarControlOperacion.setLayout(PnlRegistrarControlOperacionLayout);
        PnlRegistrarControlOperacionLayout.setHorizontalGroup(
            PnlRegistrarControlOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRegistrarControlOperacionLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(LblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlRegistrarControlOperacionLayout.setVerticalGroup(
            PnlRegistrarControlOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRegistrarControlOperacionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LblTitulo)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        LblInformeMedico.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        LblInformeMedico.setText("Informe medico:");

        LblNombreOperacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        LblNombreOperacion.setText("Nombre de la operacion:");

        LblDescripcion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        LblDescripcion.setText("Descripcion General:");

        LblResultado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        LblResultado.setText("Resultado:");

        TxtAreaDescripcion.setColumns(20);
        TxtAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(TxtAreaDescripcion);

        LblAnimal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        LblAnimal.setText("Animal:");

        javax.swing.GroupLayout PnlInformeMedicoLeftLayout = new javax.swing.GroupLayout(PnlInformeMedicoLeft);
        PnlInformeMedicoLeft.setLayout(PnlInformeMedicoLeftLayout);
        PnlInformeMedicoLeftLayout.setHorizontalGroup(
            PnlInformeMedicoLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInformeMedicoLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblInformeMedico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PnlInformeMedicoLeftLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PnlInformeMedicoLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlInformeMedicoLeftLayout.createSequentialGroup()
                        .addComponent(LblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PnlInformeMedicoLeftLayout.createSequentialGroup()
                        .addGroup(PnlInformeMedicoLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlInformeMedicoLeftLayout.createSequentialGroup()
                                .addComponent(LblAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlInformeMedicoLeftLayout.createSequentialGroup()
                                .addComponent(LblNombreOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNombreOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlInformeMedicoLeftLayout.createSequentialGroup()
                                .addComponent(LblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))))
        );
        PnlInformeMedicoLeftLayout.setVerticalGroup(
            PnlInformeMedicoLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInformeMedicoLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblInformeMedico)
                .addGap(22, 22, 22)
                .addGroup(PnlInformeMedicoLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(PnlInformeMedicoLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNombreOperacion)
                    .addComponent(TxtNombreOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(PnlInformeMedicoLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(LblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BtnModificar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlModificarLayout = new javax.swing.GroupLayout(PnlModificar);
        PnlModificar.setLayout(PnlModificarLayout);
        PnlModificarLayout.setHorizontalGroup(
            PnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlModificarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        PnlModificarLayout.setVerticalGroup(
            PnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlModificarLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        LblAnotaciones.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        LblAnotaciones.setText("Anotaciones:");

        TxtAreaAnotaciones.setColumns(20);
        TxtAreaAnotaciones.setRows(5);
        jScrollPane2.setViewportView(TxtAreaAnotaciones);

        javax.swing.GroupLayout PnlInformeMedicoRightLayout = new javax.swing.GroupLayout(PnlInformeMedicoRight);
        PnlInformeMedicoRight.setLayout(PnlInformeMedicoRightLayout);
        PnlInformeMedicoRightLayout.setHorizontalGroup(
            PnlInformeMedicoRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInformeMedicoRightLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PnlInformeMedicoRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAnotaciones))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PnlInformeMedicoRightLayout.setVerticalGroup(
            PnlInformeMedicoRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlInformeMedicoRightLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LblAnotaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlInformeMedicoLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlInformeMedicoRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PnlRegistrarControlOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlRegistrarControlOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PnlInformeMedicoRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PnlInformeMedicoLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModCtrlOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModCtrlOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModCtrlOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModCtrlOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmModCtrlOperaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnModificar;
    private javax.swing.JLabel LblAnimal;
    private javax.swing.JLabel LblAnotaciones;
    private javax.swing.JLabel LblDescripcion;
    private javax.swing.JLabel LblInformeMedico;
    private javax.swing.JLabel LblNombreOperacion;
    private javax.swing.JLabel LblResultado;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlInformeMedicoLeft;
    private javax.swing.JPanel PnlInformeMedicoRight;
    private javax.swing.JPanel PnlModificar;
    private javax.swing.JPanel PnlRegistrarControlOperacion;
    private javax.swing.JTextField TxtAnimal;
    private javax.swing.JTextArea TxtAreaAnotaciones;
    private javax.swing.JTextArea TxtAreaDescripcion;
    private javax.swing.JTextField TxtNombreOperacion;
    private javax.swing.JTextField TxtResultado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
