/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class frmMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuAdmin
     */
    public frmMenuAdmin() {
        initComponents();
        getContentPane().setBackground(new Color(204, 255, 204));
        this.setLocationRelativeTo(null);
        setResizable(false);
        setSize(1000, 620);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlTitulo = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        PnlSaludo = new javax.swing.JPanel();
        LblSaludo = new javax.swing.JLabel();
        PnlInputs = new javax.swing.JPanel();
        PnlRegistrar = new javax.swing.JPanel();
        BtnRegVet = new javax.swing.JButton();
        PnlGestionar = new javax.swing.JPanel();
        BtnGesVet = new javax.swing.JButton();
        PnlVerHistorias = new javax.swing.JPanel();
        BtnVerHist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlTitulo.setBackground(new Color(204, 255, 204));
        PnlTitulo.setLayout(new java.awt.GridBagLayout());

        LblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        LblTitulo.setText("Sistema de administradores");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 168, 30, 141);
        PnlTitulo.add(LblTitulo, gridBagConstraints);

        PnlSaludo.setBackground(new Color(204, 255, 204));

        LblSaludo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        LblSaludo.setText("¡Buenas (Tiempo), (Nombre del administrador)!");

        javax.swing.GroupLayout PnlSaludoLayout = new javax.swing.GroupLayout(PnlSaludo);
        PnlSaludo.setLayout(PnlSaludoLayout);
        PnlSaludoLayout.setHorizontalGroup(
            PnlSaludoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSaludoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(LblSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlSaludoLayout.setVerticalGroup(
            PnlSaludoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSaludoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LblSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        PnlInputs.setLayout(new java.awt.GridLayout(3, 1));

        PnlRegistrar.setBackground(new Color(204, 255, 204));
        PnlRegistrar.setLayout(new java.awt.GridBagLayout());

        BtnRegVet.setText("Registrar veterinario");
        BtnRegVet.setPreferredSize(new java.awt.Dimension(700, 80));
        BtnRegVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegVetActionPerformed(evt);
            }
        });
        PnlRegistrar.add(BtnRegVet, new java.awt.GridBagConstraints());

        PnlInputs.add(PnlRegistrar);

        PnlGestionar.setBackground(new Color(204, 255, 204));
        PnlGestionar.setLayout(new java.awt.GridBagLayout());

        BtnGesVet.setText("Gestionar veterinarios");
        BtnGesVet.setPreferredSize(new java.awt.Dimension(700, 80));
        PnlGestionar.add(BtnGesVet, new java.awt.GridBagConstraints());

        PnlInputs.add(PnlGestionar);

        PnlVerHistorias.setBackground(new Color(204, 255, 204));
        PnlVerHistorias.setLayout(new java.awt.GridBagLayout());

        BtnVerHist.setText("Ver historias médicas");
        BtnVerHist.setPreferredSize(new java.awt.Dimension(700, 80));
        PnlVerHistorias.add(BtnVerHist, new java.awt.GridBagConstraints());

        PnlInputs.add(PnlVerHistorias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PnlSaludo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PnlInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlInputs, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegVetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegVetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnGesVet;
    public javax.swing.JButton BtnRegVet;
    public javax.swing.JButton BtnVerHist;
    private javax.swing.JLabel LblSaludo;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlGestionar;
    private javax.swing.JPanel PnlInputs;
    private javax.swing.JPanel PnlRegistrar;
    private javax.swing.JPanel PnlSaludo;
    private javax.swing.JPanel PnlTitulo;
    private javax.swing.JPanel PnlVerHistorias;
    // End of variables declaration//GEN-END:variables
}
